blog/blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/users/urls.py
from django.urls import path
from django.views.generic import TemplateView

# View
from users import views


urlpatterns = [

  

    # Management
    path(
        route = 'login/', 
        view = views.login_view, 
        name='login'
    ),
    path(
        route = 'logout/', 
        view = views.logout_view, 
        name='logout'
    ),
    path(
        route = 'signup/', 
        view = views.signup, 
        name ='signup'
    ),
    path(
        route = 'me/profile/', 
        view = views.update, 
        name='update'
    ),


    # Posts
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

blog/users/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

blog/users/forms.py
# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(label=False,min_length=4,max_length=50, widget = forms.TextInput(attrs={'placeholder':'Nombre de usuario','class': 'form-control','required': True}))
    password = forms.CharField(label=False,min_length=4,max_length=70,  widget=forms.PasswordInput(attrs={'placeholder':'Contraseña','class': 'form-control','required': True}))
    password_confirmation = forms.CharField(label=False,min_length=4,max_length=70,  widget=forms.PasswordInput(attrs={'placeholder':'Repita Contraseña','class': 'form-control','required': True}))
 

    first_name = forms.CharField(label=False,min_length=2,max_length=50, widget = forms.TextInput(attrs={'placeholder':'Nombre','class': 'form-control','required': True}))
    last_name = forms.CharField(label=False,min_length=4,max_length=50, widget = forms.TextInput(attrs={'placeholder':'apellido','class': 'form-control','required': True}))
    email = forms.CharField(label=False,min_length=4,max_length=50, widget = forms.EmailInput(attrs={'placeholder':'Correo Electronico','class': 'form-control','required': True}))


    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Nombre de usuario en uso')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('contraseñas no coiciden.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


class ProfileForm(forms.Form):
    """Profile form."""

    website = forms.URLField(max_length=200, required=False)
    biography = forms.CharField(max_length=500, required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    picture = forms.ImageField(required=False)

blog/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView

# Models
from django.contrib.auth.models import User
from posts.models import Post

# Forms
from users.forms import ProfileForm, SignupForm


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

@login_required
def update(request):
    """Update a user's profile view."""
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data

            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']
            profile.save()

            return redirect('posts:feed')

    else:
        form = ProfileForm()

    return render(
        request=request,
        template_name='users/update_profile.html',
        context={
            'profile': profile,
            'user': request.user,
            'form': form
        }
    )


def login_view(request):
    """Login view."""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('posts:feed')
        else:
            return render(request, 'users/login.html', {'error': 'Usuario o contraseña invalidos'})

    return render(request, 'users/login.html')


def signup(request):
    """Sign up view."""
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = SignupForm()

    return render(
        request=request,
        template_name='users/signup.html',
        context={'form': form}
    )



@login_required
def logout_view(request):

    logout(request)
    return redirect('users:login')

blog/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
{% block head_content %}{% endblock %}
{% load static %}
<link rel="icon" type="image/jpg" href="{% static 'img/favicon.png' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
<link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>

<div class="container mt-5">
{% block container %}
{% endblock%}
</div>
</body>
</html>

blog/templates/users/detail.html
{% extends "base.html" %}
{% load static %}
{% block head_content %}
<title>@{{ user.username }} | Blog RoiBack</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center">
                {% if user.profile.picture %}
                <img src="{{ user.profile.picture.url }}" 
                alt="{{ user.username }}"
                class="rounded-circle"
                width="150px"
                />
                {% else%}
                <img src="{% static 'img/default-profile.png' %}" 
                alt="{{ user.username }}"
                class="rounded-circle"
                width="150px"
                />
                {% endif %}

            </div>

            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Editar perfil
                        </a>
                    {% else %}
                        
                    {% endif %}
                </h2>

                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-6">
                        <b>{{ user.profile.posts_count }}785</b> posts publicados
                    </div>
                    <div class="col-sm-6">
                        <b>{{ user.profile.followers }}1,401</b> Like totales
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row col-md-12">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="posts:detail" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                    <br><br>
                    <h6>{{ post.description }}</h6>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

blog/templates/users/login.html
{% extends "users/base.html" %}
{% load static %}

{% block head_content %}
<title>login</title>
{% endblock%}

{% block container %}
<a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "users:login" %}">
    <img src="{% static "img/roiback.png" %}" height="45" class="d-inline-block align-top"/>
    

</a>
<h3 class="navbar-brand pr-5"> Inicia sesiòn para acceder al blog </h3>

    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif%}

    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>


        <button class="btn btn-primary btn-block mt-5" type="submit">Logueate!</button>

    </form>
    <p class="mt-4">no tienes una cuenta aun? <a href="{% url "users:signup" %}">Resgistrate aqui!.</a></p>

{% endblock %}

blog/templates/users/signup.html
{% extends "users/base.html" %}
{% load static %}

{% block head_content %}
<title>RoiBack sign up</title>
{% endblock %}

{% block container %}
<a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "users:login" %}">
    <img src="{% static "img/roiback.png" %}" height="45" class="d-inline-block align-top"/>
    

</a>
<h3 class="navbar-brand pr-5"> Crea tu cuenta para acceder al blog </h3>

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Vamos a darle!</button>

    </form>

{% endblock %}

blog/templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Actualiza tu perfil</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4">
                            <input type="file" name="picture">
                        </p>
                            
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Imagen: </b>{{ error }}
                </div>
                {% endfor %}

                <hr><br>

                {# Website field #}
                <div class="form-group">
                    <label>sitio web</label>
                    <input
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                        type="website"
                        name="website"
                        placeholder="Website"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Biography field #}
                <div class="form-group">
                    <label>Biografia</label>
                    <textarea
                        class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography"
                    >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>

                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Phone number field #}
                <div class="form-group">
                    <label>Numero de telefono</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="number"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">actualiza tu info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}